# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a12a0ae2ffba2d67987b77e39ab2c377acd7a8b79bae1b4df57db9b1a367403b7541a583c14fc85d94416b337f9bcf364af6af77faa2974838fcbb3c7885a5b6

test:
  secret_key_base: 3ebb776038c404b4049d3c9f50a6fedd8c8dbed77113c9fcb0f233957d6c6a8511c56dbdf917ab6188caf1ab600d8734bcb71377b5e41fb641f2b3504f2a01f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
